// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfcwM2Jgmn-e4AUS54y1_riYjtJEItpzY',
    appId: '1:707732855506:web:58c9b66c2842229ad1eb0b',
    messagingSenderId: '707732855506',
    projectId: 'hydrasense-9ba6b',
    authDomain: 'hydrasense-9ba6b.firebaseapp.com',
    storageBucket: 'hydrasense-9ba6b.firebasestorage.app',
    measurementId: 'G-9N9ECGC20E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOXFzNe-KNdqfwZYFc6UumKgpUdwZfaHE',
    appId: '1:707732855506:android:c153da84ec4d0afed1eb0b',
    messagingSenderId: '707732855506',
    projectId: 'hydrasense-9ba6b',
    storageBucket: 'hydrasense-9ba6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBARXUNjfGhTts8GbRzqRlssqNWNcJ554',
    appId: '1:707732855506:ios:6a451162210e460bd1eb0b',
    messagingSenderId: '707732855506',
    projectId: 'hydrasense-9ba6b',
    storageBucket: 'hydrasense-9ba6b.firebasestorage.app',
    iosBundleId: 'com.example.sw2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBARXUNjfGhTts8GbRzqRlssqNWNcJ554',
    appId: '1:707732855506:ios:6a451162210e460bd1eb0b',
    messagingSenderId: '707732855506',
    projectId: 'hydrasense-9ba6b',
    storageBucket: 'hydrasense-9ba6b.firebasestorage.app',
    iosBundleId: 'com.example.sw2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfcwM2Jgmn-e4AUS54y1_riYjtJEItpzY',
    appId: '1:707732855506:web:96e5df3f34ad57a1d1eb0b',
    messagingSenderId: '707732855506',
    projectId: 'hydrasense-9ba6b',
    authDomain: 'hydrasense-9ba6b.firebaseapp.com',
    storageBucket: 'hydrasense-9ba6b.firebasestorage.app',
    measurementId: 'G-RNF6H8FP8J',
  );
}
